---@meta
---@class alertlist MQDatatype
---@field public AlertList MQInt #Any spawn on the associated alert list
---@field public bAlert MQBoolean #Indicates usage of alert filter
---@field public bAura MQBoolean #Any aur.
---@field public bBanker MQBoolean #Any banker
---@field public bBanner MQBoolean #Any banner
---@field public bCampfire MQBoolean #Any campfire
---@field public bDps MQBoolean #Any player that is a DPS class
---@field public bExactName MQBoolean #Name match requiries an exact match
---@field public bFellowship MQBoolean #Any member of the fellowship
---@field public bGM MQBoolean #Any player flagged as a GM
---@field public bGroup MQBoolean #Any member of the group
---@field public bHealer MQBoolean #Any player that is a healer class
---@field public bKnight MQBoolean #Any player that is a knight
---@field public bKnownLocation MQBoolean #Indicates usage of a loc filter
---@field public bLFG MQBoolean #Any player that is flagged as LFG
---@field public bLight MQBoolean #Indicates usage of a light filter
---@field public bLoS MQBoolean #Any spawn in line of sight
---@field public bMerchant MQBoolean #Any merchant
---@field public bNamed MQBoolean #Any "named" NPC
---@field public bNearAlert MQBoolean #Indicates usage of nearalert filter
---@field public bNoAlert MQBoolean #Indicates usage of noalert filter
---@field public bNoGroup MQBoolean #Exclude any player that is in the group
---@field public bNoGuild MQBoolean #Exclude any player that is in the guild
---@field public bNoPet MQBoolean #Exclude any spawn that is a pet
---@field public bNotNearAlert MQBoolean #Indicates usage of notnearalert filter
---@field public BodyType MQString #Any spawn with given body type
---@field public bRaid MQBoolean #Any member of the raid
---@field public bSlower MQBoolean #Any player that is a slower
---@field public bSpawnID MQBoolean #Indicates usage of the id filter
---@field public bTank MQBoolean #Any player that is a tank class
---@field public bTargetable MQBoolean #Any spawn that is targetable
---@field public bTargNext MQBoolean #Indicates usage of the next filter
---@field public bTargPrev MQBoolean #Indicates usage of the prev filter
---@field public bTrader MQBoolean #Any player that is a trader
---@field public bTributeMaster MQBoolean #Any NPC that is a tribute master
---@field public Class MQString #Any spawn that is the given class
---@field public FRadius MQInt #Any spawn that is given distance from the given loc filter
---@field public FromSpawnID MQInt #Search starts at given spawn id
---@field public GuildID MQInt	Any member of the guild with the given id
---@field public Light MQString #Any spawn that is equipped with the given light source
---@field public MaxLevel MQInt #Any spawn that is at this level or lower
---@field public MinLevel MQInt #Any spawn that is at this level or greater
---@field public Name MQString #Any spawn with the given name
---@field public NearAlertList MQInt #Any spawn near the given alert list
---@field public NoAlertList MQInt #Excludes any spawn in the given alert list
---@field public NotID MQInt #Excludes any spawn with the given id
---@field public NotNearAlertList MQInt #Excludes any spawn near the given alert list
---@field public PlayerState MQInt #Any spawn with the given state
---@field public Race MQString #Any spawn with the given race
---@field public Radius MQInt #Excludes the spawn if any player is within this distance (nopcnear filter)
---@field public SortBy MQInt #Indicates the sort order of the filter
---@field public Spawn MQSpawn If an ID or Name is part of the filter, attempts to return a spawn with the matching ID or Name
---@field public SpawnID MQInt #Any spawn with the given Spawn ID
---@field public SpawnType MQInt #Any spawn with the given type
---@field public xLoc MQInt #x component of the loc filter
---@field public yLoc MQInt #y component of the loc filter
---@field public ZRadius MQInt #z distance component of the loc filter