--- @class fellowship
--- @field public Campfire MQBoolean #TRUE if campfire is up, FALSE if not
--- @field public CampfireDuration ticks | fun(): ticks Time left on current campfire
--- @field public CampfireX MQFloat #Campfire X location
--- @field public CampfireY MQFloat #Campfire Y location
--- @field public CampfireZ MQFloat #Campfire Z location
--- @field public CampfireZone MQZone Zone information for the zone that contains your campfire
--- @field public ID MQInt #Fellowship ID
--- @field public Leader MQString #Fellowship leader's name
--- @field public Member fun(): fellowshipmember Member data by name or #
--- @field public Members MQInt #Number of members in the fellowship
--- @field public MotD MQString #Fellowship Message of the Day
--- @field public ToString MQString #TRUE if currently in a fellowship, FALSE if not