--- @class float
--- @field public Deci string The number as a string with one place of precision, i.e. ###.#
--- @field public Centi string The number as a string with two places of precision, i.e. ###.##
--- @field public Int number Integer portion of the number truncated rather than rounded, e.g. 12.779 returns 12
--- @field public Milli string The number as a string with three places of precision, i.e. ###.###
--- @field public Precision string The number as a string with # places of precision
--- @field public ToString string Same as Centi