---@meta

---@class ground
---@field public ID MQInt # Ground item ID (not the same as item ID, this is like spawn ID)
---@field public Distance MQFloat # Distance from player to ground item
---@field public X MQFloat # X coordinate
---@field public Y MQFloat # Y coordinate
---@field public Z MQFloat # Z coordinate
---@field public Heading MQHeading # Ground item is facing this heading
---@field public Name MQString # Name
---@field public HeadingTo MQHeading # Direction player must move to meet this ground item
---@field public LineOfSight MQBoolean # Returns TRUE if ground spawn is in line of sight
---@field public DisplayName MQFloat # Displays name of the grounspawn
---@field public Distance3D MQFloat # Distance from player to ground item
---@field public SubID MQInt # ???
---@field public ZoneID MQInt # ID of the zone
---@field public First MQGround
---@field public Last MQGround
---@field public Next MQGround
---@field public Prev MQGround
---@field public DoFace fun() # Will cause the toon to face the called for spawn if it exists
---@field public DoTarget fun() # Will cause the toon to target the called for spawn if it exists
---@field public Grab fun() # Picks up the ground spawn
---@field public W MQFloat # X coordinate (Westward-positive)
---@field public N MQFloat # Y coordinate (Northward-positive)
---@field public U MQFloat # Z coordinate (Upward-positive)
---@field public ToString MQString # Same as ID
