---@class itemspell
---@field public CastTime timestamp Cast time (unadjusted)
---@field public EffectiveCasterLevel MQInt #Effective level that is used to cast the spell.
---@field public EffectType MQInt #The type of item spell effect.
---@field public MaxCharges MQInt #The maximum number of charges supported by this spell.
---@field public OverrideDescription MQString #Overrides the normal spell description string, if set.
---@field public OverrideName MQString #Overrides the normal spell name string, if set.
---@field public ProcRate MQInt #Combat effect proc rate.
---@field public RecastType MQInt #Recast type of the spell.
---@field public RequiredLevel MQInt #Level required for the spell to be usable.
---@field public Spell MQSpell The spell.
---@field public SpellID MQInt #ID of the Spell.
---@field public TimerID MQInt #Timer ID of the spell.