---@class macroquest
---@field public BuildDate MQString #Date that MQ2Main.dll was built
---@field public BuildName MQString #Name of the build (Live, Test, Emu)
---@field public ChatChannel MQBoolean #Returns TRUE if channel name is joined
---@field public ChatChannels MQFloat #Returns the number #of channels currently joined
---@field public Error MQString #Last normal error message
---@field public GameState MQString #Returns "INGAME, CHARSELECT, PRECHARSELECT, UNKNOWN"
---@field public LastCommand MQString #Last command entered
---@field public LastTell MQString #Name of last person to send you a tell
---@field public LClickedObject MQBoolean #Returns TRUE if an object has been left clicked
---@field public LoginName MQString #Your station name
---@field public MouseX MQFloat #Mouse's X location
---@field public MouseY MQFloat #Mouse's Y location
---@field public MQ2DataError MQString #Last MQ2Data parsing error message
---@field public Path fun(relativePath?: string): string Directory that Macroquest.exe launched from. Relative path is added to the MQ directory
---@field public Ping MQFloat #Your current ping
---@field public Running MQFloat #Running time of current MQ2 session, in milliseconds
---@field public Server MQString #Full name of your server
---@field public SyntaxError MQString #Last syntax error message
---@field public ViewportX MQFloat #EverQuest viewport upper left (X) position
---@field public ViewportXCenter MQFloat #EverQuest viewport center (X) position
---@field public ViewportXMax MQFloat #EverQuest viewport lower right (X) position
---@field public ViewportY MQFloat #EverQuest viewport upper left (Y) position
---@field public ViewportYCenter MQFloat #EverQuest viewport center (Y) position
---@field public ViewportYMax MQFloat #EverQuest viewport lower right (Y) position
---@field public ToString MQString #None
