---@class plugin
---@field public Name MQString # Name of the plugin
---@field public Version MQFloat # Version number of the plugin
---@field public IsLoaded MQBoolean # Is the plugin loaded?
---@field public ToString MQString # Same as Name
