---@class taskmember
---@field public Name MQString # Returns name of the member
---@field public Leader MQBoolean # Returns true if the member is leader
---@field public Index MQInt # Returns task index for member (i.e. 1-6)