---@meta

--- @enum ImGuiWindowFlags
ImGuiWindowFlags = {
  None = 0,
  NoTitleBar = 0,
  NoResize = 0,
  NoMove = 0,
  NoScrollbar = 0,
  NoScrollWithMouse = 0,
  NoCollapse = 0,
  AlwaysAutoResize = 0,
  NoBackground = 0,
  NoSavedSettings = 0,
  NoMouseInputs = 0,
  MenuBar = 0,
  HorizontalScrollbar = 0,
  NoFocusOnAppearing = 0,
  NoBringToFrontOnFocus = 0,
  AlwaysVerticalScrollbar = 0,
  AlwaysHorizontalScrollbar = 0,
  AlwaysUseWindowPadding = 0,
  NoNavInputs = 0,
  NoNavFocus = 0,
  UnsavedDocument = 0,
  NoDocking = 0,
  NoNav = 0,
  NoDecoration = 0,
  NoInputs = 0,
  NavFlattened = 0,
  ChildWindow = 0,
  Tooltip = 0,
  Popup = 0,
  Modal = 0,
  ChildMenu = 0,
}