---@meta

---@enum ImGuiCol
ImGuiCol = {
  Text = 0, --
  TextDisabled = 0, --
  WindowBg = 0, --
  ChildBg = 0, --
  PopupBg = 0, -- Background of popups, menus
  Border = 0, --
  BorderShadow = 0, --
  FrameBg = 0, -- Background of checkbox, radio button, plot, slider
  FrameBgHovered = 0, --
  FrameBgActive = 0, --
  TitleBg = 0, --
  TitleBgActive = 0, --
  TitleBgCollapsed = 0, --
  MenuBarBg = 0, --
  ScrollbarBg = 0, --
  ScrollbarGrab = 0, --
  ScrollbarGrabHovered = 0, --
  ScrollbarGrabActive = 0, --
  CheckMark = 0, --
  SliderGrab = 0, --
  SliderGrabActive = 0, --
  Button = 0, --
  ButtonHovered = 0, --
  ButtonActive = 0, --
  Header = 0, -- Header* colors are used for CollapsingHeader, TreeNode, Selectable
  HeaderHovered = 0, --
  HeaderActive = 0, --
  Separator = 0, --
  SeparatorHovered = 0, --
  SeparatorActive = 0, --
  ResizeGrip = 0, --
  ResizeGripHovered = 0, --
  ResizeGripActive = 0, --
  Tab = 0, --
  TabHovered = 0, --
  TabActive = 0, --
  TabUnfocused = 0, --
  TabUnfocusedActive = 0, --
  PlotLines = 0, --
  PlotLinesHovered = 0, --
  PlotHistogram = 0, --
  PlotHistogramHovered = 0, --
  TableHeaderBg = 0, --
  TableBorderStrong = 0, --
  TableBorderLight = 0, --
  TableRowBg = 0, --
  TableRowBgAlt = 0, --
  TextSelectedBg = 0, --
  DragDropTarget = 0, --
  NavHighlight = 0, --
  NavWindowingHighlight = 0, --
  NavWindowingDimBg = 0, -- Darken/colorize entire screen behind the CTRL+TAB window list
  ModalWindowDimBg = 0, -- Darken/colorize entire screen behind a modal window
}