---@class AdvLoot
---@field public Filter fun(itemId:integer): itemfilterdata Inspect the loot filter for a given ItemID
---@field public LootInProgress fun(): boolean True/False if looting from AdvLoot is in progress
---@field public PCount fun(): integer Item count from the Personal list
---@field public PList fun(index:integer): advlootitem Inspect the item at the specified index in the personal loot list
---@field public PWantCount fun(): integer Want cound from the personal list (AN + AG + ND + GD)
---@field public SCount fun(): integer Item count from the Shared list
---@field public SList fun(index:integer): advlootitem Inspect the item at the specified index in the shared loot list
---@field public SWantCount fun(): integer Want count from the Shared list (AN + AG + ND + GD)