--- @class Navigation
--- @field public Active boolean Returns true if navigation is currently active
--- @field public Paused boolean Returns true if nativation is currently paused
--- @field public MeshLoaded boolean Returns true if a mesh is loaded for the zone
--- @field public PathExists boolean Returns true if a path exists for the target
--- @field public PathLength int