--- NetBots Lua Binding
--- @class NetBots
---@field Client fun(index: integer): netbot The netbot at the given index in the array
---@field Counts fun(): integer The number of connected clients.
---@field Enable fun(): boolean The plugin status.
---@field Listen fun(): boolean The grab parameter status.
---@field Output fun(): boolean The send parameter status.
