--- @class altability
--- @field public AARankRequired fun(): number Rank required to train
--- @field public CanTrain fun(): boolean Returns true/false on if the Alternative Ability can be trained
--- @field public Cost fun(): number Base cost to train
--- @field public Description fun(): string Basic description
--- @field public ID fun(): integer ID
--- @field public Index fun(): number Returns the index number of the Alternative Ability
--- @field public MaxRank fun(): number Max rank available in this ability
--- @field public MinLevel fun(): number Minimum level to train
--- @field public MyReuseTime fun(): number Reuse time with any hastened AA abilties
--- @field public Name fun(): string Name
--- @field public NextIndex fun(): number Returns the next index number of the Alternative Ability
--- @field public PointsSpent fun(): number Returns the amount of points spent on an AA
--- @field public Passive fun(): boolean Returns true/false on if the Alternative Ability is passive
--- @field public RequiresAbility altability Required ability (if any)
--- @field public Rank fun(): number Returns the Rank of the AA
--- @field public RequiresAbilityPoints fun(): number Points required in above ability
--- @field public ReuseTime fun(): number Reuse time in seconds
--- @field public ShortName fun(): string Short name
--- @field public Spell spell Spell used by the ability (if any)
--- @field public Type fun(): number Type (1-6)