--- @class altability
--- @field public AARankRequired number Rank required to train
--- @field public CanTrain boolean Returns true/false on if the Alternative Ability can be trained
--- @field public Cost number Base cost to train
--- @field public Description string Basic description
--- @field public ID number ID
--- @field public Index number Returns the index number of the Alternative Ability
--- @field public MaxRank number Max rank available in this ability
--- @field public MinLevel number Minimum level to train
--- @field public MyReuseTime number Reuse time with any hastened AA abilties
--- @field public Name string Name
--- @field public NextIndex number Returns the next index number of the Alternative Ability
--- @field public PointsSpent number Returns the amount of points spent on an AA
--- @field public Passive boolean Returns true/false on if the Alternative Ability is passive
--- @field public RequiresAbility altability Required ability (if any)
--- @field public Rank number Returns the Rank of the AA
--- @field public RequiresAbilityPoints number Points required in above ability
--- @field public ReuseTime number Reuse time in seconds
--- @field public ShortName string Short name
--- @field public Spell spell Spell used by the ability (if any)
--- @field public Type number Type (1-6)