
--- Using CachedBuff to get buff info on targets, group members etc, only requires you to target the entity once.
--- The upside is obviously that we don't have to target back and forth constantly.
---
--- Usagei
--- @class cachedbuff
--- @field public CasterName string Returns the name of the caster who applied the cached buff
--- @field public Count number Returns the amount of buffs catched, or -1 it none
--- @field public Duration number Returns the duration of the cached buff
--- @field public Slot number Returns the buff slot the target had the buff in
--- @field public SpellID number Returns the buff's spell ID