---@class class
---@field public CanCast boolean Can cast seplls, including Bard
---@field public ClericType boolean Cleric/Paladin?
---@field public DruidType boolean Druid/Ranger?
---@field public HealerType boolean Cleric/Druid/Shaman?
---@field public ID number The class's ID #
---@field public MercType boolean Mercenary?
---@field public Name string The long name, as in "Ranger"
---@field public NecromancerType boolean Necromancer/Shadow Knight?
---@field public PureCaster boolean Any one of: Cleric, Druid, Shaman, Necromancer, Wizard, Mage, Enchanter
---@field public ShamanType boolean Shaman/Beastlord?
---@field public ShortName string The short name as in "RNG"