--- @class corpse : spawn
--- @field public Item fun(item:integer):item #th item on the corpse
--- @field public Items fun():number Number of items on the corpse
--- @field public Open fun():boolean Corpse open?