--- @class corpse
--- @field public Item item #th item on the corpse
--- @field public Items number Number of items on the corpse
--- @field public Open boolean Corpse open?
--- @field public ToString boolean Same as Open