--- @class evolving
--- @field public ExpPct fun(): float Percentage of experience that the item has gained
--- @field public ExpOn MQBoolean #Is evolving item experience turned on for this item?
--- @field public Level MQInt #The level of the evolving item.
--- @field public MaxLevel MQInt #The maximum level of the evolving item
--- @field public ToString MQString #Same as ExpOn