--- @class evolving
--- @field public ExpPct float Percentage of experience that the item has gained
--- @field public ExpOn boolean Is evolving item experience turned on for this item?
--- @field public Level number The level of the evolving item.
--- @field public MaxLevel number The maximum level of the evolving item
--- @field public ToString string Same as ExpOn