--- @class fellowship
--- @field public Campfire boolean TRUE if campfire is up, FALSE if not
--- @field public CampfireDuration ticks Time left on current campfire
--- @field public CampfireX float Campfire X location
--- @field public CampfireY float Campfire Y location
--- @field public CampfireZ float Campfire Z location
--- @field public CampfireZone zone Zone information for the zone that contains your campfire
--- @field public ID number Fellowship ID
--- @field public Leader string Fellowship leader's name
--- @field public Member fellowshipmember Member data by name or #
--- @field public Members number Number of members in the fellowship
--- @field public MotD string Fellowship Message of the Day
--- @field public ToString string TRUE if currently in a fellowship, FALSE if not