--- @class fellowshipmember
--- @field public Class fun(): class Member's class
--- @field public Level fun(): integer Member's level
--- @field public LastOn fun(): ticks How long since member was last online
--- @field public Name fun(): string Member's name
--- @field public Zone zone | fun(): zone Zone information for the member's zone
--- @field public ToString fun(): string player name