--- @class heading
--- @field public Clock fun(): number The nearest clock direction, e.g. 1-12
--- @field public Degrees fun(): number Heading in degrees
--- @field public DegreesCCW fun(): number Heading in degrees counter-clockwise.  This is the way the rest of MQ and EQ uses it.
--- @field public Name fun(): string The long compass direction, e.g. "south by southeast"
--- @field public ShortName fun(): string The short compass direction, e.g. "SSE"