--- @class heading
--- @field public Clock MQFloat # The nearest clock direction, e.g. 1-12
--- @field public Degrees MQFloat # Heading in degrees
--- @field public DegreesCCW MQFloat # Heading in degrees counter-clockwise.  This is the way the rest of MQ and EQ uses it.
--- @field public Name MQString # The long compass direction, e.g. "south by southeast"
--- @field public ShortName MQString # The short compass direction, e.g. "SSE"