--- @class invslot
--- @field public ID fun(): integer ID of this item slot (usable directly by /itemnotify)
--- @field public Item item Item data for the item in this slot
--- @field public Name fun(): string For inventory slots not inside packs, the slot name, otherwise NULL
--- @field public Pack invslot Container that must be opened to access the slot with /itemnotify
--- @field public Slot fun(): integer Slot number inside the pack which holds the item, otherwise NULL
--- @field public ToString fun(): string Same as ID