--- @class skill
--- @field public Activated boolean Returns TRUE if the skill has been activated
--- @field public AltTimer boolean Returns TRUE if the skill uses the kick/bash/slam/backstab/frenzy timer
--- @field public ID number Skill number
--- @field public MinLevel number Minimum level for your class
--- @field public Name string Name of the skill
--- @field public ReuseTime number Reuse timer (what number format? ticks, seconds, deciseconds?)
--- @field public SkillCap number Skill cap based on your current level and class.
--- @field public StartingSkill number Base skill level for your class
--- @field public ToString string Same as Name