--- @class spell
--- @field public AERange MQFloat AE range (group spells use this for their range)
--- @field public CastOnAnother MQString #Message when cast on others
--- @field public CastOnYou MQString #Message when cast on yourself
--- @field public CastTime timestamp Cast time (unadjusted)
--- @field public CounterType MQString #The resist counter. Will be one of "Disease", "Poison", "Curse" or "Corruption"
--- @field public CounterNumber MQInt #The number of counters that the spell adds
--- @field public Duration ticks Duration of the spell (if any)
--- @field public DurationValue1 ticks Duration of the spell (if any)
--- @field public FizzleTime timestamp Time to recover after fizzle
--- @field public GemIcon MQInt #Icon number of the spell. Exmaple ${Spell[blah].GemIcon}
--- @field public HastePct MQFloat #Percentage of haste, example of use ${Me.Hasted.HastePct} or ${Spell[Speed of Milyex].HastePct}
--- @field public ID number Spell ID
--- @field public IsSkill MQBoolean #is this spell a skill?
--- @field public IsSwarmSpell MQBoolean #Is this spell a Swarm spell?
--- @field public Level MQInt #Level
--- @field public Location MQFloat #Appears to be max distance
--- @field public Mana MQInt #Mana cost (unadjusted)
--- @field public MyCastTime timestamp Adjusted cast time
--- @field public MyRange MQFloat Adjusted spell range, including focus effects, etc.
--- @field public Name MQString #Spell Name
--- @field public PushBack MQFloat Push back amount
--- @field public Range MQFloat Maximum range to target (use AERange for AE and group spells)
--- @field public Rank MQInt #Returns either 1, 2 or 3 for spells and 4-30 for clickys and potions.
--- @field public RankName MQString #Returns the spell/combat ability name rank character has.
--- @field public ReagentCount MQInt #Number of reagents used for this spell
--- @field public ReagentID MQInt #ID of the reagent item used for this spell
--- @field public RecastTime MQFloat #Time to recast after successful cast
--- @field public RecoveryTime timestamp Same as FizzleTime
--- @field public ResistAdj MQInt #Resist adjustment
--- @field public ResistType MQString #See below for Resist Types
--- @field public Skill MQString #See below for Skill Types
--- @field public SlowPct MQFloat #Percentage of slow, example of use ${Target.Slowed.SlowPct} or ${Spell[Slowing Helix].SlowPct}
--- @field public SpellIcon MQInt #Icon number of the spell. Exmaple ${Spell[blah].SpellIcon}
--- @field public SpellType MQString #The spell type, Will be one of "Beneficial(Group)", "Beneficial", "Detrimental" or "Unknown"
--- @field public Stacks MQBoolean #Does the selected spell stack with your current buffs (duration is in ticks)
--- @field public StacksPet MQBoolean #Does the selected spell stack with your pet's current buffs (duration is in ticks)
--- @field public StacksTarget MQBoolean #Does the selected spell stack with your target's current buffs (duration is in ticks)
--- @field public StacksWith MQBoolean #alias for .WillStack - see entry for more details
--- @field public NewStacks MQBoolean #see entry for more details
--- @field public TargetType MQString #See below for Target Types
--- @field public WearOff MQString #The "wear off" message
--- @field public WillStack fun(name: string): boolean Does the selected spell stack with the specific SPELL nameDOES NOT work with AAs.
--- @field public ToString MQString #Same as Name