--- @class target : spawn
--- @field public Aego cachedbuff|fun(): string Returns the name of the Aego spell if the Target has one
--- @field public AggroHolder spawn|fun(): spawn Returns the target's current target.
--- @field public Beneficial cachedbuff|fun(): string Returns the name of the Beneficial spell if the Target has one. This will skip "player" casted buffs, but will show NPC Casted buffs and some AA buffs.
--- @field public Buff cachedbuff|fun(): cachedbuff Returns the target's spell by buff index number or the first buff if no Index is provided.
--- @field public BuffCount fun(): integer Returns the number of buffs on the target.
--- @field public BuffDuration timestamp|fun(val:string|integer): timestamp Returns the duration remaining on this target buff by index number or by spell name
--- @field public BuffsPopulated fun(): boolean Returns TRUE when the target's buffs are finished populating.
--- @field public Brells fun(): string Returns the name of the Brells spell if the Target has one
--- @field public Charmed cachedbuff|fun(): string Returns the name of the Charmed spell if the Target has one
--- @field public Clarity cachedbuff|fun(): string Returns the name of the Clarity spell if the Target has one
--- @field public Corrupted cachedbuff|fun(): string Returns the name of any the Corruption spell if Target has one
--- @field public Cursed cachedbuff|fun(): string Returns the name of the Curse spell if Target has one
--- @field public Crippled cachedbuff|fun(): string Returns the name of the Cripple spell if the Target has one
--- @field public Diseased cachedbuff|fun(): string Returns the name of a Disease spell if the Target has one
--- @field public Dotted cachedbuff|fun(): string Returns the name of a DOT spell if the Target has one
--- @field public DSed cachedbuff|fun(): string Returns the name of the Damage Shield spell if the Target has one
--- @field public Focus cachedbuff|fun(): string Returns the name of the Focus spell if the Target has one
--- @field public Growth cachedbuff|fun(): string Returns the name of the Growth spell if the Target has one
--- @field public Hasted cachedbuff|fun(): string Returns the name of the Haste spell if the Target has one
--- @field public HybridHP cachedbuff|fun(): string Returns the name of the Hybrid HP spell if the Target has one
--- @field public Maloed cachedbuff|fun(): string Returns the name of the Malo spell if the Target has one
--- @field public Mezzed cachedbuff|fun(): string Returns the name of the Mez spell if the Target has one
--- @field public Poisoned cachedbuff|fun(): string Returns the name of a Poison spell if the Target has one
--- @field public Pred cachedbuff|fun(): string Returns the name of the Predator spell if the Target has one
--- @field public Rooted cachedbuff|fun(): string Returns the name of the Rooted spell if the Target has one
--- @field public Regen cachedbuff|fun(): string Returns the name of the Regen spell if the Target has one
--- @field public RevDSed cachedbuff|fun(): string Returns the name of the Reverse Damage Shield spell if the Target has one
--- @field public SE cachedbuff|fun(): string Returns the name of the Spiritual Enlightenment spell if the Target has one
--- @field public Shining cachedbuff|fun(): string Returns the name of the Shining spell if the Target has one
--- @field public Skin cachedbuff|fun(): string Returns the name of the Skin spell if the Target has one
--- @field public Slowed cachedbuff|fun(): string Returns the name of the Slow spell if the Target has one
--- @field public Snared cachedbuff|fun(): string Returns the name of the Snare spell if the Target has one
--- @field public Strength cachedbuff|fun(): string Returns the name of the Strength spell if the Target has one
--- @field public SV cachedbuff|fun(): string Returns the name of the Spiritual Vitality spell if the Target has one
--- @field public Symbol cachedbuff|fun(): string Returns the name of the Symbol spell if the Target has one
--- @field public Tashed cachedbuff|fun(): string Returns the name of the Tash spell if the Target has one
--- @field public ToString string Same as Name