--- @class timer
--- @field public OriginalValue fun(): integer Original value of the timer
--- @field public Value fun(): integer Current value of the timer
--- @field public ToString fun(): string Same as Value