--- @class xtarget : spawn
--- @field public ID MQInt #ID of specified XTarget
--- @field public Name MQString #Name of specified XTarget
--- @field public PctAggro MQFloat #PctAggro of specified XTarget
--- @field public TargetType MQString #Extended target type
--- @field public ToString MQString #Number of current extended targets