--- @class zone
--- @field public ID number ID of the zone
--- @field public Name string Full zone name
--- @field public ShortName string Short zone name
--- @field public ToString string Same as Name