--- @class zone
--- @field public ID MQInt #ID of the zone
--- @field public Name fun(): string Full zone name
--- @field public ShortName fun(): string Short zone name
--- @field public ToString fun(): string Same as Name